version: "3.8"

services:
  agendador-tarefas:
    build: ../agendador-tarefas
    container_name: agendador-tarefas
    ports:
      - "8081:8081"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/db_agendador
    depends_on:
      - mongo

  notificacao:
    build: ../notificacao
    container_name: notificacao
    ports:
      - "8082:8082"

  usuario:
    build: ../usuario
    container_name: usuario
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db_usuario
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - postgres

  bff-agendador-tarefas:
    build: .
    container_name: bff-agendador-tarefas
    ports:
      - "8083:8083"
    environment:
      USUARIO_URL: http://usuario:8080/usuario
      AGENDADOR_TAREFAS_URL: http://agendador-tarefas:8081/tarefas
      NOTIFICACAO_URL: http://notificacao:8082/email
    depends_on:
      - usuario
      - agendador-tarefas
      - notificacao

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_usuario
    ports:
      - "5433:5432"

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: db_agendador

networks:
  default:
    driver: bridge
